In [1]:
import numpy as np
import math
import sympy as sp
import random
import operator
gg = np.array([[5, 5, 100, 100], [150, 5, 200, 80], [150, 150, 220, 80,], [5, 150, 100, 200]])
# np.set_printoptions(suppress=True)

In [2]:
A = np.array([[-gg[0][0], -gg[0][1], -1, 0, 0, 0, gg[0][0]*gg[0][2], gg[0][1]*gg[0][2], gg[0][2]], [0, 0, 0, -gg[0][0], -gg[0][1], -1, gg[0][0]*gg[0][3], gg[0][1]*gg[0][3], gg[0][3]], 
              [-gg[1][0], -gg[1][1], -1, 0, 0, 0, gg[1][0]*gg[1][2], gg[1][1]*gg[1][2], gg[1][2]], [0, 0, 0, -gg[1][0], -gg[1][1], -1, gg[1][0]*gg[1][3], gg[1][1]*gg[1][3], gg[1][3]],
              [-gg[2][0], -gg[2][1], -1, 0, 0, 0, gg[2][0]*gg[2][2], gg[2][1]*gg[2][2], gg[2][2]], [0, 0, 0, -gg[2][0], -gg[2][1], -1, gg[2][0]*gg[2][3], gg[2][1]*gg[2][3], gg[2][3]],
              [-gg[3][0], -gg[3][1], -1, 0, 0, 0, gg[3][0]*gg[3][2], gg[3][1]*gg[3][2], gg[3][2]], [0, 0, 0, -gg[3][0], -gg[3][1], -1, gg[3][0]*gg[3][3], gg[3][1]*gg[3][3], gg[3][3]]])

In [3]:
A

array([[   -5,    -5,    -1,     0,     0,     0,   500,   500,   100],
       [    0,     0,     0,    -5,    -5,    -1,   500,   500,   100],
       [ -150,    -5,    -1,     0,     0,     0, 30000,  1000,   200],
       [    0,     0,     0,  -150,    -5,    -1, 12000,   400,    80],
       [ -150,  -150,    -1,     0,     0,     0, 33000, 33000,   220],
       [    0,     0,     0,  -150,  -150,    -1, 12000, 12000,    80],
       [   -5,  -150,    -1,     0,     0,     0,   500, 15000,   100],
       [    0,     0,     0,    -5,  -150,    -1,  1000, 30000,   200]])

In [4]:
x = np.empty((9, 1))

In [5]:
rank = np.linalg.matrix_rank(A)
A_t = A.transpose()
P = np.matmul(A, A_t)
Q = np.matmul(A_t, A)

In [6]:
eig_val_P, eig_vec_P = np.linalg.eig(P)
eig_vec_P = np.matrix(eig_vec_P)
print(type(eig_vec_P))
eig_val_Q, eig_vec_Q = np.linalg.eig(Q)
eig_vec_Q = np.matrix(eig_vec_Q)
eig_vec_Q_trans = np.transpose(eig_vec_Q)
print(type(eig_vec_Q_trans))


<class 'numpy.matrix'>
<class 'numpy.matrix'>


In [7]:
print(eig_vec_P)

[[ 1.17519867e-02  3.44207228e-04 -5.15532162e-02 -4.66128587e-01
  -2.60345896e-01 -6.78428560e-02 -8.41087769e-01  1.08122924e-02]
 [ 1.17517760e-02  3.43641967e-04 -8.72103737e-02 -4.59351955e-01
  -2.49098952e-01 -8.85591890e-02  3.54169472e-01  7.65455993e-01]
 [ 3.58735699e-01  6.54942912e-01  1.34538659e-02 -4.65084492e-01
   1.70101644e-01  2.93617516e-01  1.82289868e-01 -2.78385484e-01]
 [ 1.43494223e-01  2.61976394e-01 -4.45383120e-01  1.36060221e-01
  -5.00795526e-01 -5.87488150e-01  1.52897235e-01 -2.73099287e-01]
 [ 7.74962678e-01  2.27117371e-02  4.08516159e-01  2.84937362e-01
   3.19642679e-02 -2.35211438e-01 -1.59658351e-01  2.62688692e-01]
 [ 2.81806634e-01  8.24745878e-03 -6.92167142e-01  3.15915567e-01
   1.14149714e-02  5.01908806e-01 -1.69560615e-01  2.46628160e-01]
 [ 1.84643411e-01 -3.16806256e-01  2.48466337e-01 -3.46544961e-02
  -6.98268275e-01  4.67261587e-01  1.81630339e-01 -2.52393736e-01]
 [ 3.69278450e-01 -6.33614920e-01 -2.88917222e-01 -3.93333286e-01
   

In [8]:
print(eig_val_P)

[3.62583363e+09 1.01280011e+09 6.80651927e+04 3.46776193e+04
 2.12012335e+04 3.70648899e+03 6.56490974e-01 1.52001454e+01]


In [9]:
def Swap(arr, start_index, last_index):
    arr[:, [start_index, last_index]] = arr[:, [last_index, start_index]]

In [10]:
Swap(eig_vec_P, 6, 7)
print(eig_vec_P)

[[ 1.17519867e-02  3.44207228e-04 -5.15532162e-02 -4.66128587e-01
  -2.60345896e-01 -6.78428560e-02  1.08122924e-02 -8.41087769e-01]
 [ 1.17517760e-02  3.43641967e-04 -8.72103737e-02 -4.59351955e-01
  -2.49098952e-01 -8.85591890e-02  7.65455993e-01  3.54169472e-01]
 [ 3.58735699e-01  6.54942912e-01  1.34538659e-02 -4.65084492e-01
   1.70101644e-01  2.93617516e-01 -2.78385484e-01  1.82289868e-01]
 [ 1.43494223e-01  2.61976394e-01 -4.45383120e-01  1.36060221e-01
  -5.00795526e-01 -5.87488150e-01 -2.73099287e-01  1.52897235e-01]
 [ 7.74962678e-01  2.27117371e-02  4.08516159e-01  2.84937362e-01
   3.19642679e-02 -2.35211438e-01  2.62688692e-01 -1.59658351e-01]
 [ 2.81806634e-01  8.24745878e-03 -6.92167142e-01  3.15915567e-01
   1.14149714e-02  5.01908806e-01  2.46628160e-01 -1.69560615e-01]
 [ 1.84643411e-01 -3.16806256e-01  2.48466337e-01 -3.46544961e-02
  -6.98268275e-01  4.67261587e-01 -2.52393736e-01  1.81630339e-01]
 [ 3.69278450e-01 -6.33614920e-01 -2.88917222e-01 -3.93333286e-01
   

In [11]:
sigma = np.sqrt(eig_val_P)
sigma[::-1].sort()
print(type(sigma))
sigma_matrix = np.diag(sigma)
print(sigma_matrix)


<class 'numpy.ndarray'>
[[6.02148954e+04 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 3.18245207e+04 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.60893068e+02 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.86219278e+02
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.45606434e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 6.08809411e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 3.89873638e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000

In [12]:

new_col = [0, 0, 0, 0, 0, 0, 0, 0]
sigma_matrix = np.insert(sigma_matrix, 8, new_col, axis = 1)
print((sigma_matrix))

[[6.02148954e+04 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 3.18245207e+04 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.60893068e+02 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.86219278e+02
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.45606434e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 6.08809411e+01 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 3.89873638e+00 0.00000000e+00
  0.00000000e+00]
 [0.00

In [13]:
##### for checking answer
u, s, vh = np.linalg.svd(A, full_matrices=True)
print(vh)
print(eig_vec_P - u)

[[-2.84043894e-03 -2.42121739e-03 -2.20891154e-05 -1.09109680e-03
  -1.63479471e-03 -1.33908907e-05  6.96053715e-01  7.17950893e-01
   6.16016024e-03]
 [-3.14430147e-03  1.28321626e-03 -1.13495064e-05 -1.17416448e-03
   2.90636016e-03  1.14077892e-05  7.17961695e-01 -6.96067270e-01
  -2.29933343e-05]
 [ 2.46384735e-01  3.77000733e-01  2.37217168e-03 -6.61240940e-01
  -5.74279813e-01 -5.80190908e-03  7.57487350e-05 -1.62813209e-03
   1.73453679e-01]
 [ 1.58554932e-01 -1.76600215e-01  3.65660431e-03 -3.41172744e-01
   7.10405325e-02  2.15181510e-03  3.79564118e-03  3.77529395e-03
  -9.06741660e-01]
 [-1.75245114e-01  6.89508147e-01  5.19584361e-03  5.01749740e-01
  -3.14549320e-01  2.88147957e-03  2.50334194e-03  2.49754245e-03
  -3.78319687e-01]
 [-1.76705635e-01 -5.90273326e-01 -7.52000216e-03  2.32499365e-01
  -7.49883366e-01  5.73504703e-03  1.50223526e-04 -3.65599795e-03
  -6.21986452e-02]
 [ 9.13738625e-01 -5.29344506e-02  6.59901593e-02  3.72052358e-01
  -6.19835401e-02 -1.2248990

In [14]:
last_column = eig_vec_Q[:, -1]
homo = np.reshape(last_column, (3, 3))
print(homo)

[[ 5.31056349e-02 -4.91718842e-03  6.14648552e-01]
 [ 1.77018783e-02 -3.93375074e-03  7.86750146e-01]
 [ 2.36025044e-04 -4.91718842e-05  7.62164204e-03]]
